### ISSUE TITLE
Blaze library unusable in online version

### ISSUE THREAD

**Issue by FabienPean** [mattgodbolt/compiler-explorer-image#95] opened 2018-07-16 12:48 UTC
Just including the library seems to exceed the compilation time allowed.

```c++
#include<blaze/Blaze.h>
int square(int num) {
    return num * num;
}
```
Compilation output: 
> Killed - processing time exceeded
> Compiler returned: -1

After ~7500ms, tested with clang 6.0 and gcc 8.1

**Comment by mattgodbolt** [comment] 2018-07-16 23:52
This is unfortunate and is probably related to #53 - our network file system is not fast enough to handle the read traffic in a timely fashion for big template libraries.

I ran the command on one of the compilation nodes directly under time and it took 22 seconds...

**Comment by mattgodbolt** [comment] 2018-11-29 23:01
Closing as a duplicate of #53

**Closed by mattgodbolt** 2018-11-29 23:01 UTC
